### ISSUE TITLE
Build the latest releases from git

### ISSUE THREAD

**Issue by Ray-V** [Ray-V/tde-slackbuilds#10]
@olevenets2 wrote:

> How about adding the ability to build the latest releases from git?

I think that the sources could be pulled from the git repository and used in the build script.

The question is what to pull down.

[1] Individual package archives to the latest commit
For: only download for the apps required
Against: a new commit entails downloading the complete archive again.

[2] The complete repo
For: incremental updates to reduce amount of future downloads
Against: a huge and slow download initially and unwanted apps stored

I believe that a 'sparse checkout' may be possible for the apps required, but I've not looked at that in detail.

**Comment by olevenets2** [comment]
Hi, **Ray-V**! 
Individual package + checking for new commits for applications seems to be the most optimal option in this case.

**Comment by Ray-V** [comment]
I've made a start on including a build option for development [git] sources.

This is set up in 'gitbuild' branch, which includes a brief README-git listing the packages tested and known to work so far.

@olevenets2
Re: your issue with the mouse wheel, in issue <a href="https://github.com/Ray-V/tde-slackbuilds/issues/6#issuecomment-392133733">#6</a>, it's OK in the git build.

**Comment by olevenets2** [comment]
The problem with scrolling is really solved, great!

I tested the script and got an error:

tdenetwork.SlackBuild FAILED at line 49

it's line:

    -DCMAKE_C_FLAGS:STRING="$SLKCFLAGS $TQT_INCLUDE_PATH"

**Comment by olevenets2** [comment]
Hi, the error with scrolling in konsole is solved, excellent!

I tested gitbuild-script, with tdenetwork error when configuring:


Run Build Command:"/usr/bin/gmake" "cmTC_eff6f/fast"
/usr/bin/gmake -f CMakeFiles/cmTC_eff6f.dir/build.make CMakeFiles/cmTC_eff6f.dir/build
gmake[1]: вход в каталог «/tmp/build/tmp-tdenetwork/tdenetwork/build-tdenetwork/CMakeFiles/CMakeTmp»
Building C object CMakeFiles/cmTC_eff6f.dir/CheckIncludeFile.c.o
/usr/bin/clang    -O2 -fPIC -march=core2 -mtune=core2 -I/opt/trinity/lib64/tqt3/include    -o CMakeFiles/cmTC_eff6f.dir/CheckIncludeFile.c.o   -c /tmp/build/tmp-tdenetwork/tdenetwork/build-tdenetwork/CMakeFiles/CMakeTmp/CheckIncludeFile.c
/tmp/build/tmp-tdenetwork/tdenetwork/build-tdenetwork/CMakeFiles/CMakeTmp/CheckIncludeFile.c:1:10: fatal error: 'sys/sockio.h' file not found
#include <sys/sockio.h>
         ^
1 error generated.

It looks like it can not find the file sockio.h. Do you have any idea how this can be fixed?

**Comment by Ray-V** [comment]
All packages built by BUILD-TDE.sh now checked and SlackBuilds edited where needed.

The only build failure is kdbusnotification:

In file included from daemon.moc.cpp:9:0:
../../../src/daemon/daemon.h:25:42: error: expected initializer before ‘:’ token
 class TDEUI_EXPORT NotificationContainer : public TDEPassivePopupStackContainer
                                          ^

which I haven't been able to fix.

<hr>

Re: the 'sockio.h' error   

I did all the testing for git builds with gcc, but I've done a clang build for tdenetwork and it completed ok.

That error was shown in the CMakeError.log for my build. I don't know much about cmake, but experience has taught me that only means that test failed and whatever it was needed for therefore won't be included in the build - not that the build failed. I think the actual build failure will be shown in the CMakeOutput.log.

The tdenetwork git build includes a new dependency libtdevnc and it may be that was causing your build failure. But now I've updated all the scripts, I suggest you start again to see if the tdenetwork build still fails.

**Comment by olevenets2** [comment]
Hi, try compiling kdbusnotification with this patch, maybe this will help

--- a/src/daemon/daemon.cpp
+++ b/src/daemon/daemon.cpp
@@ -31,6 +31,7 @@
#include <knotifyclient.h>
#include <tdeaboutdata.h>
#include <tdecmdlineargs.h>
+#include <tdeglobal.h>
#include <tdelocale.h>
#include <tdeapplication.h>
#include <kiconloader.h>

there are also mkspecs for build with Clang
https://mirror.git.trinitydesktop.org/cgit/tqt3/commit/?id=1de74439

**Comment by olevenets2** [comment]
Hi, you need to fix CC/CCX value for k9copy and soundkonverter since these packages work with clang! Fixed also kdbusnotification and my patch for krusader was added, it is not necessary to add it to the tree. 

And you will need to correct the description in the KNOWN-ISSUES file since now all packages are compiled with clang.

**Comment by Ray-V** [comment]
Thanks for the info.

I've merged the gitbuild branch into master now and included those updates for k9copy and soundkonverter SlackBuilds.
