### ISSUE TITLE
kvpnc build issue

### ISSUE THREAD

**Issue by Ndolam** [Ray-V/tde-slackbuilds#11]
Hi, I tried to build kvpnc (weeks after building the main system and various other optional things).
This is what I get:

Script started on Wed 03 Oct 2018 12:52:24 PM ADT

 removing previous build data ..

 unpacking kvpnc-R14.0.5.tar.bz2 ... 

*** automake (GNU automake) 1.15 found.
*** Creating acinclude.m4
make[1]: Entering directory '/tmp/build/tmp-kvpnc/applications/kvpnc'
make[1]: Leaving directory '/tmp/build/tmp-kvpnc/applications/kvpnc'
*** Creating list of subdirectories
make[1]: Entering directory '/tmp/build/tmp-kvpnc/applications/kvpnc'
cd . && make -f admin/Makefile.common subdirs
make[2]: Entering directory '/tmp/build/tmp-kvpnc/applications/kvpnc'
make[2]: Leaving directory '/tmp/build/tmp-kvpnc/applications/kvpnc'
make[1]: Leaving directory '/tmp/build/tmp-kvpnc/applications/kvpnc'
*** Creating configure.files
*** Creating configure.in
make[1]: Entering directory '/tmp/build/tmp-kvpnc/applications/kvpnc'
cd . && make -f admin/Makefile.common configure.in ;
make[2]: Entering directory '/tmp/build/tmp-kvpnc/applications/kvpnc'
make[2]: Leaving directory '/tmp/build/tmp-kvpnc/applications/kvpnc'
make[1]: Leaving directory '/tmp/build/tmp-kvpnc/applications/kvpnc'
*** Creating aclocal.m4
aclocal: warning: autoconf input should be named 'configure.ac', not 'configure.in'
acinclude.m4:6988: warning: the serial number must appear before any macro definition
/usr/share/aclocal/libxosd.m4:9: warning: underquoted definition of AM_PATH_LIBXOSD
/usr/share/aclocal/libxosd.m4:9:   run info Automake 'Extending aclocal'
/usr/share/aclocal/libxosd.m4:9:   or see http://www.gnu.org/software/automake/manual/automake.html#Extending-aclocal
configure.in:53: warning: AC_REQUIRE: `AC_PROG_CPP' was expanded before it was required
configure.in:53: http://www.gnu.org/software/autoconf/manual/autoconf.html#Expanded-Before-Required
../../lib/autoconf/c.m4:336: AC_LANG_PREPROC(C) is expanded from...
../../lib/autoconf/lang.m4:372: AC_LANG_PREPROC_REQUIRE is expanded from...
../../lib/autoconf/general.m4:2538: AC_EGREP_CPP is expanded from...
../../lib/autoconf/general.m4:2556: AC_EGREP_HEADER is expanded from...
../../lib/m4sugar/m4sh.m4:639: AS_IF is expanded from...
../../lib/autoconf/general.m4:2031: AC_CACHE_VAL is expanded from...
../../lib/autoconf/general.m4:2052: AC_CACHE_CHECK is expanded from...
../../lib/autoconf/headers.m4:677: AC_HEADER_STDC is expanded from...
../../lib/autoconf/headers.m4:297: _AC_INCLUDES_DEFAULT_REQUIREMENTS is expanded from...
../../lib/autoconf/headers.m4:353: AC_INCLUDES_DEFAULT is expanded from...
../../lib/autoconf/lang.m4:224: AC_LANG_SOURCE is expanded from...
../../lib/autoconf/lang.m4:241: AC_LANG_PROGRAM is expanded from...
../../lib/autoconf/lang.m4:193: AC_LANG_CONFTEST is expanded from...
../../lib/autoconf/general.m4:2729: _AC_RUN_IFELSE is expanded from...
../../lib/m4sugar/m4sh.m4:639: AS_IF is expanded from...
../../lib/autoconf/general.m4:2748: AC_RUN_IFELSE is expanded from...
../../lib/m4sugar/m4sh.m4:639: AS_IF is expanded from...
../../lib/autoconf/general.m4:2031: AC_CACHE_VAL is expanded from...
../../lib/autoconf/general.m4:2052: AC_CACHE_CHECK is expanded from...
../../lib/autoconf/c.m4:1444: AC_C_BIGENDIAN is expanded from...
acinclude.m4:3428: AC_CHECK_COMPILERS is expanded from...
configure.in:53: the top level
*** Creating configure
configure.in:53: warning: AC_REQUIRE: `AC_PROG_CPP' was expanded before it was required
configure.in:53: http://www.gnu.org/software/autoconf/manual/autoconf.html#Expanded-Before-Required
../../lib/autoconf/c.m4:336: AC_LANG_PREPROC(C) is expanded from...
../../lib/autoconf/lang.m4:372: AC_LANG_PREPROC_REQUIRE is expanded from...
../../lib/autoconf/general.m4:2538: AC_EGREP_CPP is expanded from...
../../lib/autoconf/general.m4:2556: AC_EGREP_HEADER is expanded from...
../../lib/m4sugar/m4sh.m4:639: AS_IF is expanded from...
../../lib/autoconf/general.m4:2031: AC_CACHE_VAL is expanded from...
../../lib/autoconf/general.m4:2052: AC_CACHE_CHECK is expanded from...
../../lib/autoconf/headers.m4:677: AC_HEADER_STDC is expanded from...
../../lib/autoconf/headers.m4:297: _AC_INCLUDES_DEFAULT_REQUIREMENTS is expanded from...
../../lib/autoconf/headers.m4:353: AC_INCLUDES_DEFAULT is expanded from...
../../lib/autoconf/lang.m4:224: AC_LANG_SOURCE is expanded from...
../../lib/autoconf/lang.m4:241: AC_LANG_PROGRAM is expanded from...
../../lib/autoconf/lang.m4:193: AC_LANG_CONFTEST is expanded from...
../../lib/autoconf/general.m4:2729: _AC_RUN_IFELSE is expanded from...
../../lib/m4sugar/m4sh.m4:639: AS_IF is expanded from...
../../lib/autoconf/general.m4:2748: AC_RUN_IFELSE is expanded from...
../../lib/m4sugar/m4sh.m4:639: AS_IF is expanded from...
../../lib/autoconf/general.m4:2031: AC_CACHE_VAL is expanded from...
../../lib/autoconf/general.m4:2052: AC_CACHE_CHECK is expanded from...
../../lib/autoconf/c.m4:1444: AC_C_BIGENDIAN is expanded from...
acinclude.m4:3428: AC_CHECK_COMPILERS is expanded from...
configure.in:53: the top level
*** Creating config.h template
configure.in:53: warning: AC_REQUIRE: `AC_PROG_CPP' was expanded before it was required
configure.in:53: http://www.gnu.org/software/autoconf/manual/autoconf.html#Expanded-Before-Required
../../lib/autoconf/c.m4:336: AC_LANG_PREPROC(C) is expanded from...
../../lib/autoconf/lang.m4:372: AC_LANG_PREPROC_REQUIRE is expanded from...
../../lib/autoconf/general.m4:2538: AC_EGREP_CPP is expanded from...
../../lib/autoconf/general.m4:2556: AC_EGREP_HEADER is expanded from...
../../lib/m4sugar/m4sh.m4:639: AS_IF is expanded from...
../../lib/autoconf/general.m4:2031: AC_CACHE_VAL is expanded from...
../../lib/autoconf/general.m4:2052: AC_CACHE_CHECK is expanded from...
../../lib/autoconf/headers.m4:677: AC_HEADER_STDC is expanded from...
../../lib/autoconf/headers.m4:297: _AC_INCLUDES_DEFAULT_REQUIREMENTS is expanded from...
../../lib/autoconf/headers.m4:353: AC_INCLUDES_DEFAULT is expanded from...
../../lib/autoconf/lang.m4:224: AC_LANG_SOURCE is expanded from...
../../lib/autoconf/lang.m4:241: AC_LANG_PROGRAM is expanded from...
../../lib/autoconf/lang.m4:193: AC_LANG_CONFTEST is expanded from...
../../lib/autoconf/general.m4:2729: _AC_RUN_IFELSE is expanded from...
../../lib/m4sugar/m4sh.m4:639: AS_IF is expanded from...
../../lib/autoconf/general.m4:2748: AC_RUN_IFELSE is expanded from...
../../lib/m4sugar/m4sh.m4:639: AS_IF is expanded from...
../../lib/autoconf/general.m4:2031: AC_CACHE_VAL is expanded from...
../../lib/autoconf/general.m4:2052: AC_CACHE_CHECK is expanded from...
../../lib/autoconf/c.m4:1444: AC_C_BIGENDIAN is expanded from...
acinclude.m4:3428: AC_CHECK_COMPILERS is expanded from...
configure.in:53: the top level
*** Creating Makefile templates
automake: warning: autoconf input should be named 'configure.ac', not 'configure.in'
configure.in:53: warning: AC_REQUIRE: `AC_PROG_CPP' was expanded before it was required
configure.in:53: http://www.gnu.org/software/autoconf/manual/autoconf.html#Expanded-Before-Required
../../lib/autoconf/c.m4:336: AC_LANG_PREPROC(C) is expanded from...
../../lib/autoconf/lang.m4:372: AC_LANG_PREPROC_REQUIRE is expanded from...
../../lib/autoconf/general.m4:2538: AC_EGREP_CPP is expanded from...
../../lib/autoconf/general.m4:2556: AC_EGREP_HEADER is expanded from...
../../lib/m4sugar/m4sh.m4:639: AS_IF is expanded from...
../../lib/autoconf/general.m4:2031: AC_CACHE_VAL is expanded from...
../../lib/autoconf/general.m4:2052: AC_CACHE_CHECK is expanded from...
../../lib/autoconf/headers.m4:677: AC_HEADER_STDC is expanded from...
../../lib/autoconf/headers.m4:297: _AC_INCLUDES_DEFAULT_REQUIREMENTS is expanded from...
../../lib/autoconf/headers.m4:353: AC_INCLUDES_DEFAULT is expanded from...
../../lib/autoconf/lang.m4:224: AC_LANG_SOURCE is expanded from...
../../lib/autoconf/lang.m4:241: AC_LANG_PROGRAM is expanded from...
../../lib/autoconf/lang.m4:193: AC_LANG_CONFTEST is expanded from...
../../lib/autoconf/general.m4:2729: _AC_RUN_IFELSE is expanded from...
../../lib/m4sugar/m4sh.m4:639: AS_IF is expanded from...
../../lib/autoconf/general.m4:2748: AC_RUN_IFELSE is expanded from...
../../lib/m4sugar/m4sh.m4:639: AS_IF is expanded from...
../../lib/autoconf/general.m4:2031: AC_CACHE_VAL is expanded from...
../../lib/autoconf/general.m4:2052: AC_CACHE_CHECK is expanded from...
../../lib/autoconf/c.m4:1444: AC_C_BIGENDIAN is expanded from...
acinclude.m4:3428: AC_CHECK_COMPILERS is expanded from...
configure.in:53: the top level
configure.in:43: warning: AM_INIT_AUTOMAKE: two- and three-arguments forms are deprecated.  For more info, see:
configure.in:43: http://www.gnu.org/software/automake/manual/automake.html#Modernize-AM_005fINIT_005fAUTOMAKE-invocation
doc/Makefile.am:6: error: required directory doc/tdeioslave does not exist
doc/Makefile.am:6: error: required directory doc/en does not exist
src/Makefile.am:91: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS')
automake: warning: autoconf input should be named 'configure.ac', not 'configure.in'
admin/Makefile.common:10: recipe for target 'cvs' failed
make: *** [cvs] Error 1

Script done on Wed 03 Oct 2018 12:52:27 PM ADT

It is not immediately obvious to me what I am doing wrong.  Before I hunt around, can anyone point out my error, assuming it is my error?

Thanks

**Comment by Ray-V** [comment]
This looks like a repeat of the issue#36 you raised on Thorn-Inurcide tde-slackbuilds.

My response was:

>Looks like this is the problem:
>
>> doc/Makefile.am:6: error: required directory doc/tdeioslave does not exist  
>> doc/Makefile.am:6: error: required directory doc/en does not exist  
>
>The original doc/Makefile.am from the source archive is:
>
>> KDE_LANG = "en de fr sv"  
>> KDE_DOCS = kvpnc  
>> SUBDIRS = $(AUTODIRS)  
>
>and for an en-US only build this is overwritten by the SB script, lines 50-52, to give:
>
>> KDE_LANG = en  
>> KDE_DOCS = kvpnc  
>> SUBDIRS = tdeioslave en  
>
>If there are no 'tdeioslave en' directories in 'doc', go back to lines 38-42 in the SB - do you have an alias for 'rm' on your system which is removing the directories?

I don't have a copy of your response but I seem to remember that the problem was with 'rm'.
