### ISSUE TITLE
Fails to build

### ISSUE THREAD

**Issue by vitacell** [Ray-V/tde-slackbuilds#12]
TERMINAL OUTPUT:
make[1]: se sale del directorio '/tmp/build/tmp-tqt3/dependencies/tqt3'
../../get-source.sh: línea 303: makepkg: no se encontró la orden
Script terminado; el fichero es /tmp/tqt3-build-log

      Error:  tqt3 package build failed
      Check the build log /tmp/tqt3-build-log

LOG:
make[1]: se sale del directorio '/tmp/build/tmp-tqt3/dependencies/tqt3'
../../get-source.sh: línea 303: makepkg: no se encontró la orden (command not found)

GET-SOURCE.SH (line 303):
makepkg --linkadd y --chown n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD.${PKGTYPE:-txz} 

----------------------------------------------------------
makepkg reminds to me something about ArchLinux.

**Comment by Ray-V** [comment]
makepkg is part of the Slackware a/pkgtools-\*-noarch-\*.txz package, which also includes installpkg which I assume you must have used to set up the system in the first place.

I suggest the first thing to try is to reinstall pkgtools and then run 'makepkg --help' to check whether it's been installed, and is in the PATH.

**Comment by vitacell** [comment]
Thanks for your answer. It is my fault. I did not "su". Newbie in Slackware, got used to ArchLinux. I have compiled Trinity, thanks for that well built project.

**Comment by vitacell** [comment]
Something is wrong when building, I already installed imlib and imlib2 from SlackBuilds. I rerun the script but still same results.

Terminal output: http://dpaste.com/0HZH06V
/tmp/imlib-build-log: http://dpaste.com/3EDDX2S

20 days ago I could to build TDE with your program, in Slackware in VM, but now I can no to do it.

**Comment by Ray-V** [comment]
It looks as though your problem is building gdk-imlib, which requires gtk+-1.

I don't have that installed and so don't get the build error.

Do you need gdk-imlib - imlib seems to work OK for kuickshow without it, and the Imlib README states:

"Also note that gdk-imlib WILL NOT WORK with GTK2.  It won't even compile.
This is not a bug.  This is a feature.  If you need an image loader for GTK2,
use gdk-pixbuf."

BTW - files can be attached here, there's no need to use a third-party service.

**Comment by vitacell** [comment]
Hi, I could to compile finally. But it doesn't configure automatically to boot with TDM(login display manager). What I did is read this 
https://www.slackbook.org/html/x-window-system-xdm.html
for info, now I understand how display manager selection does work in Slackware. Of course I also did "chmod -x /opt/trinity/bin/tdm" and "chmod 777 /opt/trinity/bin/tdm".

Yes, I removed "imlib" and "gtk+1.2", not sure but maybe gtk+1.2 comes with Slackware by default, I installed and removed binary TDE package from here 
https://sourceforge.net/projects/tde-slackware/files/TDE-14.0.5_SL14.2/
it does work, but they don't have complete/full version for compile. Thanks for your help.

**Comment by fastname3** [comment]
hello
 has nothing to do with this but do you think upgrading script to R14.0.6??
thanks bye

**Comment by Ray-V** [comment]
To upgrade the build to R14.0.6 needs the source code available - the script uses the repositories @ https://mirror.ppa.trinitydesktop.org/trinity/releases/

The source for R14.0.5 took 10 days to be released, but for R14.0.6 there's still no sign after 14 days.

But I share your frustration, so I've added the option to build r14.0.6 from the snapshot archives @ https://git.trinitydesktop.org/cgit/

**Comment by fastname3** [comment]
yes still not uploaded the source code
I try to install the git version but is version 14.1.0 DEV I expected a 14.0.6
now to wait 
thanks bye

**Comment by vitacell** [comment]
Do you guys use TDE? and love it? 
I have one question, is here some way to add more widget themes (I mean GTK controls/widget analoge)(is named qtcurve?)? this is the only thing I hate about KDE in general.

Thanks to Ray-V for making that great compiling script!

**Comment by fastname3** [comment]
vitacell look here to see if you find something similar
https://www.trinity-look.org/
