### ISSUE TITLE
Now building fails

### ISSUE THREAD

**Issue by vitacell** [Ray-V/tde-slackbuilds#13]
http://dpaste.com/2EDM2EP

I already have installed "htdig" and rebooted. But did not help.

**Comment by Ray-V** [comment]
Sorry for the delay in responding, I've been away.
The above link has expired, please post details as an attachment here.

**Comment by vitacell** [comment]
Sorry, my fault, just dpasted with 7 days of expire. Just close it please, becase I don't remember what was failing. Now I have new build errors, and I will report them.
