### ISSUE TITLE
xmedcon missing, build fails

### ISSUE THREAD

**Issue by vitacell** [Ray-V/tde-slackbuilds#14]
http://dpaste.com/3BZQPXZ

Fails because they, removed xmedcon-0.15.0 older version. Installer script can not it to download anymore.
So version and link to it, are wrong.

Here is a fixed SlackBuild:
http://dpaste.com/07FFS50

**Comment by Ray-V** [comment]
Thanks for the info - I'll update the version in the next script update.

I'll keep the existing URL though as there are fewer redirects with that and the second URL eventually redirects to it anyway:

VERSION=${VERSION:-0.16.2}

[1]  
SRCURL="https://downloads.sourceforge.net/project/xmedcon/XMedCon-Source/$VERSION/xmedcon-$VERSION.tar.bz2"  
wget $SRCURL  
--2019-08-23 12:03:18--  `https://downloads.sourceforge.net/project/xmedcon/XMedCon-Source/0.16.2/xmedcon-0.16.2.tar.bz2`  
Resolving downloads.sourceforge.net... 216.105.38.13  
Connecting to downloads.sourceforge.net|216.105.38.13|:443... connected.  
HTTP request sent, awaiting response... 302 Found  
Location: https://netcologne.dl.sourceforge.net/project/xmedcon/XMedCon-Source/0.16.2/xmedcon-0.16.2.tar.bz2 [following]  
--2019-08-23 12:03:21--  https://netcologne.dl.sourceforge.net/project/xmedcon/XMedCon-Source/0.16.2/xmedcon-0.16.2.tar.bz2  
Resolving netcologne.dl.sourceforge.net... 78.35.24.46 
Connecting to netcologne.dl.sourceforge.net|78.35.24.46|:443... connected.  
HTTP request sent, awaiting response... 200 OK  
Length: 836840 (817K) [application/octet-stream]  
Saving to: ‘xmedcon-0.16.2.tar.bz2’  
  
xmedcon-0.16.2.tar.bz2 100%[==========================>] 817.23K  5.02MB/s    in 0.2s  
  
2019-08-23 12:03:21 (5.02 MB/s) - ‘xmedcon-0.16.2.tar.bz2’ saved [836840/836840]  



[2]  
SRCURL="https://sourceforge.net/projects/xmedcon/files/XMedCon-Source/$VERSION/xmedcon-$VERSION.tar.bz2"  
wget $SRCURL  
--2019-08-23 12:03:21--  https://sourceforge.net/projects/xmedcon/files/XMedCon-Source/0.16.2/xmedcon-0.16.2.tar.bz2  
Resolving sourceforge.net... 216.105.38.13  
Connecting to sourceforge.net|216.105.38.13|:443... connected.  
HTTP request sent, awaiting response... 301 Moved Permanently  
Location: https://sourceforge.net/projects/xmedcon/files/XMedCon-Source/0.16.2/xmedcon-0.16.2.tar.bz2/ [following]  
--2019-08-23 12:03:22--  https://sourceforge.net/projects/xmedcon/files/XMedCon-Source/0.16.2/xmedcon-0.16.2.tar.bz2/  
Reusing existing connection to sourceforge.net:443.  
HTTP request sent, awaiting response... 302 Found  
Location: https://sourceforge.net/projects/xmedcon/files/XMedCon-Source/0.16.2/xmedcon-0.16.2.tar.bz2/download [following]  
--2019-08-23 12:03:22--  https://sourceforge.net/projects/xmedcon/files/XMedCon-Source/0.16.2/xmedcon-0.16.2.tar.bz2/download  
Reusing existing connection to sourceforge.net:443.  
HTTP request sent, awaiting response... 302 Found  
Location: https://downloads.sourceforge.net/project/xmedcon/XMedCon-Source/0.16.2/xmedcon-0.16.2.tar.bz2?r=&ts=1565865201&use_mirror=datapacket [following]  
--2019-08-23 12:03:22--  `https://downloads.sourceforge.net/project/xmedcon/XMedCon-Source/0.16.2/xmedcon-0.16.2.tar.bz2`?r=&ts=1565865201&use_mirror=datapacket  
Resolving downloads.sourceforge.net... 216.105.38.13  
Connecting to downloads.sourceforge.net|216.105.38.13|:443... connected.  
HTTP request sent, awaiting response... 302 Found  
Location: https://datapacket.dl.sourceforge.net/project/xmedcon/XMedCon-Source/0.16.2/xmedcon-0.16.2.tar.bz2 [following]  
--2019-08-23 12:03:23--  https://datapacket.dl.sourceforge.net/project/xmedcon/XMedCon-Source/0.16.2/xmedcon-0.16.2.tar.bz2  
Resolving datapacket.dl.sourceforge.net... 185.152.64.70  
Connecting to datapacket.dl.sourceforge.net|185.152.64.70|:443... connected.  
HTTP request sent, awaiting response... 200 OK  
Length: 836840 (817K) [application/octet-stream]  
Saving to: ‘xmedcon-0.16.2.tar.bz2’  
  
xmedcon-0.16.2.tar.bz2 100%[==========================>] 817.23K   205KB/s    in 4.0s  
  
2019-08-23 12:03:29 (205 KB/s) - ‘xmedcon-0.16.2.tar.bz2’ saved [836840/836840]

**Comment by Ray-V** [comment]
Fixed with commit ee37f09
