### ISSUE TITLE
koffice-i18n-ru doesn't exist, build fails

### ISSUE THREAD

**Issue by vitacell** [Ray-V/tde-slackbuilds#15]
BUILD-LOG: http://dpaste.com/15W23HS
TERMINAL OUTPUT: http://dpaste.com/3YNFHZY

What is wrong? How to fix?:
You typed "cd ../" instead of "cd ../.." in /tde-slackbuilds-master/Apps/koffice-i18n/koffice-i18n.SlackBuild at line 69, fix it please.

**Comment by Ray-V** [comment]
OK I'll do that.

**Comment by vitacell** [comment]
At least this worked for me with "es ru" languages (with space).

**Comment by Ray-V** [comment]
Fixed with commit ee37f09
