### ISSUE TITLE
let's don't touch system's config

### ISSUE THREAD

**Issue by yurytch** [Ray-V/tde-slackbuilds#24]
There's an unpleasant moment in TDE-BUILD.sh, which is you can't opt out of modifying your system's configuration. It's either runlevel 3 or 4. And 'tdebase' just goes ahead and changes rc.4.local which might be already used for something, after all.
I'd suggest merging something like the following (rather primitive, but the idea should be clear):
[u.diff.txt](https://github.com/Ray-V/tde-slackbuilds/files/6496495/u.diff.txt)

**Comment by Ray-V** [comment]
Revised and fixed with commit 2dcbecf
