### ISSUE TITLE
Misc/graphviz SRCURL Error

### ISSUE THREAD

**Issue by bhoffpauir** [Ray-V/tde-slackbuilds#26]
Hello, graphviz version 2.46.1 seems to no longer be available at the OSUOSL mirror. It seems that the archive type changed to .tar.gz as well.

Misc/graphviz/graphviz.SlackBuild(Line 34):
https://github.com/Ray-V/tde-slackbuilds/blob/79c7137d9d40951bb31596a3d5be137c6828547b/Misc/graphviz/graphviz.SlackBuild#L34

Thank you,
    cppimmo/Brian

**Comment by Ray-V** [comment]
Strange that, sites usually keep old versions online and there are even older versions still available.

This patch works for me - the checksum of the gitlab file is the same as from osuosl.

```diff
--- Misc/graphviz/graphviz.SlackBuild
+++ Misc/graphviz/graphviz.SlackBuild
@@ -34 +34,3 @@
-SRCURL="https://ftp.osuosl.org/pub/blfs/conglomeration/graphviz/graphviz-$VERSION.$ARCHIVE_TYPE"
+#SRCURL="https://ftp.osuosl.org/pub/blfs/conglomeration/graphviz/graphviz-$VERSION.$ARCHIVE_TYPE"
+SRCURL="https://gitlab.com/graphviz/graphviz/-/package_files/7097037/download"
+#SRCURL="https://gitlab.com/api/v4/projects/4207231/packages/generic/graphviz-releases/2.50.0/graphviz-2.50.0.tar.xz"
```

I won't update the SlackBuild yet - I'll see how v2.50.0 works out.  
It builds ok, but that's as far as I've gone.

**Comment by Ray-V** [comment]
Updated version to 2.50.0, and changed SRCURL to gitlab
