### ISSUE TITLE
14.0.12 successful build (and a teensy note)

### ISSUE THREAD

**Issue by yurytch** [Ray-V/tde-slackbuilds#27]
Congratulations and thank you, Ray, for your great work!

Have just built and installed the 14.0.12 base, libs, sdk, tdevelop, and inkscape, too.
Not one glitch in the config and build.
Of course, I knew about problematic places in advance, and sort of went softly there, but still.

One teensy note. The dialog screen which deals with the matter of
`But tdepim, ksquirrel, tdevelop, and ktorrent need additional libraries`
is somewhat unclear as to what it wants to achieve, because of 
1. It speaks of libraries but in the list there are 'nodocs' and 'mkspecs', too.
2. It isn't very clear from the context where the additional libraries for those packages would go. 
In the respective packages? In the TQT3?

**Comment by Ray-V** [comment]
>Not one glitch in the config and build.

That's good to know.

>Of course, I knew about problematic places in advance, and sort of went softly there, but still.

In addition to what follows? - in which case, what are they?

>It isn't very clear from the context where the additional libraries for those packages would go.  
In the respective packages? In the TQT3?

In tqt3 - this screen refers to the tqt3 build, and its content.

I don't like to have unnecessary files in my system, and I've added the option to reduce the tqt3 build to the executables and libraries needed to provide the TDE desktop.

If a 'minimal' build is selected, a number of executables and libraries are excluded from the tqt3 package.  
However, if any or all of tdepim, ksquirrel, tdevelop, and ktorrent are required by a user, some of those libraries have to be included in the tqt3 package.

So they're not additional libraries to tqt3, but libraries additional to a minimal build.

>It speaks of libraries but in the list there are 'nodocs' and 'mkspecs', too.

The 'tree' presentation with the box drawing characters is meant to represent the dependency of selecting the libraries required by tdepim...ktorrent ***if*** 'minimal' is selected. And the note at the bottom of the screen which is displayed when any of the tdepim...ktorrent options is highlighted is an attempt to further clarify that.

The nodocs and mkspecs options are separate and independent.

Would something like this be clearer?

<pre>
┌────────────────────── TQt3 installation options ────────────────────────┐
│                                                                         │
│ The TQt3 installation can be packaged to include only the files         │
│ required to run TDE.                                                    │
│                                                                         │
│ There are three options:                                                │
│                                                                         │
│ [1] Keep only executables and libraries required by most applications.  │
│     This will remove libraries needed by tdepim, ksquirrel, tdevelop,   │
│ and ktorrent, so if they are required, the sub-options override the     │
│ removal of those libraries.                                             │
│                                                                         │
│ [2] Remove documentation which occupies ~21M.                           │
│                                                                         │
│ [3] Keep only mkspecs which are needed for linux-g++ or clang builds.   │
│                                                                         │
│ ┌─────────────────────────────────────────────────────────────────────┐ │
│ │       [ ]  minimal   Minimal executables and libraries              │ │
│ │       <b><span style="color:white">[ ] <span style="background-color:#1818B2"> pim_ksq</span>   <span style="background-color:#1818B2"> ├─ Keep lib for tdepim and/or ksquirrel</span></span></b>       │ │
│ │       [ ]  tdevel     ├─ Keep libs for tdevelop                     │ │
│ │       [ ]  ktorrent   └─ Keep designer libs for ktorrent            │ │
│ │       [*]  nodocs    Exclude html documentation                     │ │
│ │       [*]  mkspecs   Keep for linux-g++ or clang only               │ │
│ └─────────────────────────────────────────────────────────────────────┘ │
│                                                                         │
├─────────────────────────────────────────────────────────────────────────┤
│                               <  OK  >                                  │
└─────────────────────────────────────────────────────────────────────────┘

<span style="color:#4effff;background-color:black">  <b>Option if minimal packaging selected</b>                                     </span>
</pre>

**Comment by yurytch** [comment]
> > Of course, I knew about problematic places in advance, and sort of went softly there, but still.
> In addition to what follows? - in which case, what are they?

Excluding the rc.4 related dialog (which looks okay) and the 'TQT3 installation options', which I'd like to discuss separately, here they are (actually, both minor and not so minor annoyances, bunched together):

=Action on failure
somewhat better phrasing IMO:
If one of the selected SlackBuilds fails, do you want the process to <Stop> or to <Continue> to the next SlackBuild? 

=Temporary build files
Text goes: 'the default is to remove [tmp files]...' 
Choices are about keeping tmp files.
This is confusing.

Also here: the 'Action on failure' talked about 'SlackBuilds'. This dialog talks about 'package builds'. 

Also here: one probably doesn't (or couldn't) remember what the 'previous screen' was about; better to refer to its matter explicitly.

I suggest redoing the dialog as follows: 
1. Move explanation on why one might want to purge the tmp files from the previous SlackBuild to the 1st paragraph
2. Remove the 'The default is to remove...' paragraph altogether.
3. Make buttons say 'Keep' and 'Purge' (or 'Clean')

=Setting PKG_CONFIG_PATH
Paragraphs 1 and 2 are not very clear on what's going to happen.
'Duplicated paths' (which ones? pointing to TDE's dirs?) removed from where?
And to what benefit?
I couldn't understand the matter and just went with the 3rd paragraph reassurance and selected 'Leave'.

= Gcc visibility (should be 'Gcc hidden visibility', I think, too)
The connection between enabling this for the 'Required' part and other parts is unclear (2nd paragraph). Like, can one mix 'hidden visibility' in 'Required' and no such feature in dependants?

= Only download sources
Description for 'No' would better look along the lines of 'Regular downloading and building'.

**Comment by yurytch** [comment]
...and about that 'TQT3 installation options' dialog.

I personally do not see much sense in space minimisation by not including modules. Those extra libs add like nothing, compared.
Also, such processing produces TQT3 packages which are identical in names but different in functionality.

I would build the TQT3 complete in that respect by default, and provide the minimisation option.

But you're the boss here.

On the other hand, I can totally relate to reducing filesystem clutter by leaving out html docs and extra mkspecs (lots and lots of small files, IIRC).

So, about the dialog as such, I would suggest something different.

= TQt3 installation options
The TQt3 build is minimised by default and does not include several library modules, which are needed by some of the extra TDE applications (a little list). 
Also, the html documentation and mkspecs (those not needed by linux-g++ and clang) are not included by default.
The default minimal build will work fine if you don't use the applications from the list.
```

│ ┌─────────────────────────────────────────────────────────────────────┐ │
│ │       [ ]  pim_ksq   Add module for tdepim and/or ksquirrel         │ │
│ │       [ ]  tdevel    Add modules for tdevelop                       │ │
│ │       [ ]  ktorrent  Add modules for ktorrent                       │ │
│ │       [ ]  nodocs    Include html documentation                     │ │
│ │       [ ]  mkspecs   Include extra mkspecs (for ... compilers)      │ │
│ └─────────────────────────────────────────────────────────────────────┘ │

```
