### ISSUE TITLE
'Could not start tdeinit. Check your installation'

### ISSUE THREAD

**Issue by dchmelik** [Ray-V/tde-slackbuilds#29]
On Slackware64 15.1-current everything except InkScape (unnecessary for now) builds but starting TDE says: Could not start tdeinit. Check your installation.
        Later I could maybe upload InkScape build error log but already have newer version from SlackBuilds.org or alienBOB...

**Comment by Ray-V** [comment]
> InkScape ... newer version

Thanks for the info. I've updated the SlackBuild for Inkscape 1.2.1 and double-conversion 3.2.0

> On Slackware64 15.1-current everything except InkScape (unnecessary for now) builds

This latest version of Inkscape builds and runs for me, as did the previous version.  
Attach your build log here, and I'll see if I can help.

> TDE says: Could not start tdeinit. Check your installation.

I've never had any trouble with running TDE.  
I'll help you troubleshoot if I can, but will obviously need more -  
* is this the first time you've built TDE
	* if not, has it run before
		* did it run with an earlier release of Slackware
* did you enable the options in tdebase to set up TDE to launch as the default desktop
	* or have you set it up after installation

.. that sort of information, and any error logs.

I would think the first step should be as it says - `Check your installation`

**Comment by dchmelik** [comment]
I built TDE before and it ran (not necessarily from my build) on Slackware for years.
        My default desktop always has been and will be command-line.
        'Check your installation' is a vague/incomplete error message (and what logs? Finding exact Xorg*.log may be difficult because I'm running XFCE same time but guess I could exit and try).
