### ISSUE TITLE
kword depend on kspread for koffice?

### ISSUE THREAD

**Issue by Randrianasulu** [Ray-V/tde-slackbuilds#31]
I foolishly tried to build only kword and krita from koffice, and build end like this:

```
make[4]: выход из каталога «/tmp/build/tmp-koffice/koffice-trinity-14.0.12/build-koffice/kword/mailmerge/tdeabc»                                Making all in kspread   
 make[4]: вход в каталог «/tmp/build/tmp-koffice/koffice-trinity-14.0.12/build-koffice/kword/mailmerge/kspread»                                  /usr/bin/tmoc ../../../../kword/mailmerge/kspread/kwmailmerge_kspread.h -o kwmailmerge_kspread.moc                                              /usr/bin/tmoc ../../../../kword/mailmerge/kspread/kwmailmerge_kspread_config.h -o kwmailmerge_kspread_config.moc             
make[4]: *** Нет правила для сборки цели «../../../kspread/libkspreadcommon.la», требуемой для «kwmailmerge_kspread.la».  Останов.              
make[4]: *** Ожидание завершения заданий…       
make[4]: выход из каталога «/tmp/build/tmp-koffice/koffice-trinity-14.0.12/build-koffice/kword/mailmerge/kspread» 
make[3]: *** [Makefile:826: all-recursive] Ошибка 1     
make[3]: выход из каталога «/tmp/build/tmp-koffice/koffice-trinity-14.0.12/build-koffice/kword/mailmerge»       
make[2]: *** [Makefile:1396: all-recursive] Ошибка 1   
make[2]: выход из каталога «/tmp/build/tmp-koffice/koffice-trinity-14.0.12/build-koffice/kword»        
make[1]: *** [Makefile:696: all-recursive] Ошибка 1    
make[1]: выход из каталога «/tmp/build/tmp-koffice/koffice-trinity-14.0.12/build-koffice»                                                     
  make: *** [Makefile:613: all] Ошибка 2                                
  Script done.                                                                                                                                          Error:  koffice package build failed                           
         Check the build log /tmp/koffice-14.0.12-i586-1-build-log
```

I tried to edit kspread back into list of office applications but it does not appear to have effect?

otherwise, build works even on 'evolved' Slackware installation suffering some fallout from *.la files removal between 14.2 and 15.0 (I compiled few things locally, and they left few la files around with dependences no longer provided in updated upstream packages. some sort of png14 cleaning script from Gentoo slowly cures this problem)

Thanks a lot for buildscripts! Previously I used self-supported mix of kde 3.5.10 slackbuilds and Trinity patches. But nice dialog-based megascript very nice to have!

**Comment by Ray-V** [comment]
I can't see a way round this - kspread will need to be built if kword is selected.

I've tried a build with this patch, and it works ok.  
If kword is selected to be built, then kspread will also be built regardless of whether it's selected in the dialog list.
```diff
--- Apps/koffice/koffice.SlackBuild
+++ Apps/koffice/koffice.SlackBuild
@@ -123,0 +124,3 @@
+## issue #31 - if kword is selected, ensure kspread is built
+[[ $(cat $TMPVARS/DO_NOT_COMPILE) != *kword* ]] && sed -i 's|kspread||' $TMPVARS/DO_NOT_COMPILE
+
```

**Comment by Randrianasulu** [comment]
thanks, I manually edited this DO_NOT_COMPILE file and build worked. Will you push fix like this or build script can handle dependencies already?

ps: it was announced TDE 14.0.13 will be released soon 
https://mail.trinitydesktop.org/mailman3/hyperkitty/list/announcements@trinitydesktop.org/message/HQIPBLUJELHORFBN52W733NPGXPDC3JR/

**Comment by Ray-V** [comment]
The build script can already work ok if kspread is selected in the build options. This fix applies if kword is chosen without kspread and I'll add it to the koffice.SlackBuild on the next update, which will probably now be for the 14.0.13 release.

**Comment by Randrianasulu** [comment]
I was thinking about possible inconsistence between what user selected in ui and what actually compiles. So, if possible having kspread autoselect itself in dialog's ui will be great. (like it done in kernel config) If too hard - just adding message on koffice screen might be enough (if screen has enough space!)
