### ISSUE TITLE
tqt3-14.0.13 error on Slackware 15.0 i586?

### ISSUE THREAD

**Issue by Randrianasulu** [Ray-V/tde-slackbuilds#32]
For some reason few themes are missing and inspecting log I found those lines

```
cc1plus: error: one or more PCH files were found, but they were invalid
 cc1plus: note: use -Winvalid-pch for more information  
 <command-line>: fatal error: tqtdesignercore: No such file or directory
```

should I upload full log somewhere?

**Comment by Ray-V** [comment]
What themes are you expecting and don't get?

The invalid file is the one for tqtdesignercore, but the tqtdesignercore library is successfully built later in the build process without the use of the precompiled header.  
The use of precompiled headers can be turned off with `-no-pch` in the ./configure options, with an increase in build time.

Either way, the final packages are identical.

**Comment by Randrianasulu** [comment]
default tde theme was missing, but not due to tqt3 miscompilation - I just re-run script without  normal for me setarch i686 ( I use 64-bit kernel with 32bit userspace), and so various components in thdebase complained about incompatible build configuration (in logs).

Mass rebuild in one go fixed that. Sorry!
