### ISSUE TITLE
Unable to build without cups

### ISSUE THREAD

**Issue by HexagonWin** [Ray-V/tde-slackbuilds#33]
Hello. I'm on Slackware 15 on amd64.
I have attempted to build TDE, almost exactly following the guide at https://ray-v.github.io/A_typical_TDE_SlackBuild.html .
However after downloading the sources and when I rerun the script and start compiling it almost immediately fails with the following error on /tmp/tqt3-14.0.13-x86_64-1-build-log :
```
Script started on 2023-02-06 18:38:06+09:00 [TERM="xterm" TTY="/dev/pts/3" COLUMNS="172" LINES="59"]

 removing previous build data ..

 unpacking tqt3-14.0.13.tar.xz ...

ls: cannot access 'tqt3*/CMakeLists.txt': No such file or directory
patching file mkspecs/linux-g++/qmake.conf
Cups support cannot be enabled due to functionality tests!
 Turn on verbose messaging (-v) to ./configure to see the final report.
 If you believe this message is in error you may use the continue
 switch (-continue) to ./configure to continue.
tqt3.SlackBuild FAILED at line 126

Script done on 2023-02-06 18:38:08+09:00 [COMMAND_EXIT_CODE="101"]
```
I do not have CUPS installed on my system and I would prefer not to, since I do not have a printer at all. Is there a way to continue the build without installing the CUPS libraries?

**Comment by Ray-V** [comment]
> Is there a way to continue the build without installing the CUPS libraries?

Yes  
Edit line 147 ` -cups \` in tqt3.SlackBuild to ` -no-cups \`.

This is a ./configure option. If you run `./configure --help` you'll see that there are other `-no` options available, which might be useful to you if there are other packages you don't have installed.
